services:
  dev:
    image: php:8.2-fpm
    container_name: dev
    tty: true
    stdin_open: true
    volumes:
      - ./work:/work
    working_dir: /work
    ports:
      - "8000:8000"
      - "5173:5173"

